repos:
  - repo: local
    hooks:
      - id: create requirements
        name: create requirements
        language: system
        entry: python utils/write_requirements.py
        always_run: true
        pass_filenames: false
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        types: [markdown]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
